#!/usr/bin/env python3
"""Test script for Scene Image Prompt Builder."""

import asyncio
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from module.scene_image_prompt_builder import SceneImagePromptBuilder
from module import my_config


async def test_scene_image_prompt_builder():
    """Test scene image prompt builder with mock game context."""
    print("Testing Scene Image Prompt Builder...")
    
    try:
        # Load configurations
        scene_config = my_config.load_scene_image_config()
        main_config = my_config.load_config()  # Need main config for LLM settings
        print(f"✅ Scene image config loaded")
        
        # Initialize prompt builder with main config (contains LLM settings)
        builder = SceneImagePromptBuilder(main_config)
        print(f"✅ Prompt builder initialized")
        
        # Mock game memory context (based on GameMemoryStore.get_context_for_prompt structure)
        mock_context = {
            "player_name": "Adventurer",
            "turn_count": 5,
            "current_room": "West of House",
            "current_scene": {
                "room_name": "West of House",
                "description_lines": ["You are standing in an open field west of a white house", "with a boarded front door."],
                "current_items": ["mailbox", "leaflet"],
                "scene_items": ["mailbox", "leaflet", "door"],
                "npcs": [],
                "visit_count": 2,
                "narrations": ["The classic starting location of the great underground empire."],
                "action_records": []
            },
            "player_state": {
                "inventory": ["brass lantern"],
                "score": 0,
                "moves": 5,
                "name": "Adventurer"
            },
            "turn_hints": {
                "command": "west",
                "engine_excerpt": "arrived from the forest path"
            }
        }
        print(f"✅ Mock context created")
        
        # Test meta-prompt generation for LLM
        prompt_spec = builder.build_meta_prompt(memory_context=mock_context)
        
        print(f"✅ Meta-prompt generated for LLM:")
        print(f"  Room: {prompt_spec.metadata['room_name']}")
        print(f"  Template used: {prompt_spec.metadata['template_used']}")
        print(f"  Context extracted:")
        for key, value in prompt_spec.metadata['extracted_context'].items():
            print(f"    - {key}: '{value}'")
        print()
        print(f"  Generated LLM prompt:")
        print(f"    \"{prompt_spec.meta_prompt}\"")
        print()
        print(f"  Character count: {len(prompt_spec.meta_prompt)} chars")
        print()
        
        # Generate actual SD prompt via LLM
        print("🔄 Calling LLM to generate SD prompt...")
        sd_prompt = await builder.generate_sd_prompt(memory_context=mock_context)
        
        print(f"✅ SD prompt generated by LLM:")
        print(f"  SD Prompt: \"{sd_prompt}\"")
        print(f"  Length: {len(sd_prompt)} chars")
        print()
        
        # Validate the prompt contains expected elements
        assert prompt_spec.metadata['room_name'] == "West of House"
        assert "West of House" in prompt_spec.meta_prompt
        assert "mailbox" in prompt_spec.meta_prompt or "leaflet" in prompt_spec.meta_prompt
        print(f"✅ Validation passed - prompt contains room and items")
        
        return True
        
    except Exception as e:
        print(f"❌ Test failed: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = asyncio.run(test_scene_image_prompt_builder())
    sys.exit(0 if success else 1)